import { Link } from "react-router-dom";
import { ArrowRightCircle, Heart } from "lucide-react";
import { cn } from "@/lib/utils";

export interface AITool {
  id: string;
  name: string;
  category: string;
  description: string;
  imageUrl: string;
  upvotes: number;
  tags: string[];
}

interface AIProductCardProps {
  tool: AITool;
  className?: string;
}

export default function AIProductCard({ tool, className }: AIProductCardProps) {
  return (
    <article
      className={cn(
        "group relative flex flex-col overflow-hidden rounded-3xl border border-neutral-100 bg-white shadow-sm transition-all duration-300 hover:-translate-y-2 hover:shadow-xl",
        className,
      )}
    >
      <div className="relative aspect-square w-full overflow-hidden md:aspect-video">
        <img
          src={tool.imageUrl}
          alt={`Visual output generated by ${tool.name}`}
          className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
          loading="lazy"
          decoding="async"
        />

        <div className="absolute inset-0 flex flex-col justify-between bg-gradient-to-t from-neutral-900/80 to-transparent p-6 opacity-0 transition-opacity group-hover:opacity-100">
          <div className="flex items-center justify-between gap-4">
            <span className="rounded-full bg-white/10 px-3 py-1 text-sm font-bold uppercase tracking-wide text-white backdrop-blur-sm">
              {tool.category}
            </span>
            <button
              type="button"
              className="rounded-full bg-white/20 p-2.5 text-white backdrop-blur-sm transition-colors hover:bg-white/30"
              aria-label={`Like ${tool.name}`}
            >
              <Heart size={20} />
            </button>
          </div>
          <p className="line-clamp-3 text-sm text-white">{tool.description}</p>
        </div>
      </div>

      <div className="flex flex-grow flex-col justify-between space-y-4 p-6">
        <div>
          <h2 className="mb-1 line-clamp-2 text-xl font-extrabold tracking-tight text-neutral-950">
            {tool.name}
          </h2>
          <div className="flex flex-wrap items-center gap-2">
            {tool.tags.map((tag) => (
              <span
                key={tag}
                className="rounded-full border border-neutral-200 bg-neutral-100 px-3 py-1 text-xs font-semibold tracking-wider text-neutral-700"
              >
                {tag}
              </span>
            ))}
          </div>
        </div>

        <div className="flex items-center justify-between gap-4">
          <div className="flex items-center gap-1.5 font-semibold text-neutral-600">
            <Heart size={18} className="text-blue-600" />
            {tool.upvotes} Upvotes
          </div>

          <Link
            to={`/tool/${tool.id}`}
            className="inline-flex items-center gap-2 rounded-full bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-blue-700"
          >
            TRY FREE
            <ArrowRightCircle size={18} />
          </Link>
        </div>
      </div>
    </article>
  );
}
