-- =============================================
-- Nabdh AI Schema V4.0
-- Description: Core schema for AI Agents, Workflows, and Analytics
-- =============================================

-- 1. ENHANCED AGENTS TABLE
-- We alter the existing table to add new V4 columns instead of dropping it to preserve data
ALTER TABLE public.agents 
ADD COLUMN IF NOT EXISTS developer_id UUID REFERENCES public.profiles(id),
ADD COLUMN IF NOT EXISTS short_description TEXT,
ADD COLUMN IF NOT EXISTS avatar_url TEXT,
ADD COLUMN IF NOT EXISTS category TEXT,
ADD COLUMN IF NOT EXISTS capabilities JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS pricing_model TEXT DEFAULT 'free', -- free, pay_per_use, subscription
ADD COLUMN IF NOT EXISTS price NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_published BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS config_schema JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Update RLS for Agents
DROP POLICY IF EXISTS "Allow public read access for agents" ON public.agents;
CREATE POLICY "Public read published agents" ON public.agents FOR SELECT USING (is_published = true OR developer_id = auth.uid());
CREATE POLICY "Developers can manage their agents" ON public.agents FOR ALL USING (auth.uid() = developer_id);

-- 2. WORKFLOWS TABLE
CREATE TABLE IF NOT EXISTS public.workflows (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    definition JSONB NOT NULL DEFAULT '{}'::jsonb, -- ReactFlow nodes/edges structure
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.workflows ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage own workflows" ON public.workflows FOR ALL USING (auth.uid() = user_id);

-- 3. TASK LOGS TABLE
CREATE TABLE IF NOT EXISTS public.task_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id),
    agent_id UUID REFERENCES public.agents(id),
    workflow_id UUID REFERENCES public.workflows(id),
    status TEXT NOT NULL, -- pending, running, completed, failed
    input_data JSONB,
    output_data JSONB,
    error_message TEXT,
    execution_time INTERVAL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.task_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users view own logs" ON public.task_logs FOR SELECT USING (auth.uid() = user_id);
-- Allow system/functions to insert logs (needs service role, or authenticated insert)
CREATE POLICY "Users insert own logs" ON public.task_logs FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 4. USAGE ANALYTICS TABLE
CREATE TABLE IF NOT EXISTS public.usage_analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id UUID NOT NULL, -- Tool or Agent ID
    entity_type TEXT NOT NULL, -- 'tool' or 'agent'
    event_type TEXT NOT NULL, -- 'view', 'click', 'execution'
    user_id UUID REFERENCES auth.users(id),
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.usage_analytics ENABLE ROW LEVEL SECURITY;
-- Analytics are usually read by admins only, inserted by everyone
CREATE POLICY "Anyone can insert analytics" ON public.usage_analytics FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins view analytics" ON public.usage_analytics FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin') -- Assuming role column exists or similar check
);

-- Notify schema update
COMMENT ON TABLE public.agents IS 'Stores AI Agents with V4 market capabilities';
COMMENT ON TABLE public.workflows IS 'Stores user defined ReactFlow workflows';
