-- Migration: Quality Improvements for Tools
-- Date: 2026-01-04
-- Description: Add multi-category support, click tracking, and enhanced metadata

-- =============================================================================
-- 1. MULTI-CATEGORY SUPPORT (Secondary Categories)
-- =============================================================================

-- Add secondary_categories column if not exists
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                 WHERE table_name = 'tools' AND column_name = 'secondary_categories') THEN
    ALTER TABLE public.tools 
    ADD COLUMN secondary_categories TEXT[] DEFAULT '{}';
  END IF;
END $$;

COMMENT ON COLUMN public.tools.secondary_categories IS 'Array of additional categories for the tool (allows multi-category listing)';

-- Create index for secondary categories search
CREATE INDEX IF NOT EXISTS idx_tools_secondary_categories 
ON public.tools USING GIN (secondary_categories);

-- =============================================================================
-- 2. ENHANCED CLICK TRACKING
-- =============================================================================

-- Create a table for detailed click tracking (for affiliate analytics)
CREATE TABLE IF NOT EXISTS public.tool_clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_id INTEGER NOT NULL REFERENCES public.tools(id) ON DELETE CASCADE,
  clicked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  referrer TEXT,
  user_agent TEXT,
  ip_hash TEXT -- Hashed IP for privacy compliance
);

-- RLS for tool_clicks
ALTER TABLE public.tool_clicks ENABLE ROW LEVEL SECURITY;

-- Anyone can insert clicks (tracking)
CREATE POLICY "allow_insert_clicks" ON public.tool_clicks
  FOR INSERT TO anon, authenticated
  WITH CHECK (true);

-- Only admins can read click data
CREATE POLICY "admin_read_clicks" ON public.tool_clicks
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Index for analytics queries
CREATE INDEX IF NOT EXISTS idx_tool_clicks_tool_id ON public.tool_clicks(tool_id);
CREATE INDEX IF NOT EXISTS idx_tool_clicks_clicked_at ON public.tool_clicks(clicked_at);

-- =============================================================================
-- 3. FUNCTION TO UPDATE CLICKS COUNT
-- =============================================================================

-- Function to record a click and update counter
CREATE OR REPLACE FUNCTION public.record_tool_click(
  p_tool_id INTEGER,
  p_referrer TEXT DEFAULT NULL,
  p_user_agent TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Insert click record
  INSERT INTO public.tool_clicks (tool_id, user_id, referrer, user_agent)
  VALUES (p_tool_id, auth.uid(), p_referrer, p_user_agent);
  
  -- Update clicks_count in tools table
  UPDATE public.tools 
  SET clicks_count = COALESCE(clicks_count, 0) + 1
  WHERE id = p_tool_id;
END;
$$;

-- Grant execute permission
GRANT EXECUTE ON FUNCTION public.record_tool_click TO anon, authenticated;

-- =============================================================================
-- 4. ADD USE CASES FIELD IF NOT EXISTS
-- =============================================================================

-- The 'tasks' column already exists for use cases, but let's ensure it
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                 WHERE table_name = 'tools' AND column_name = 'tasks') THEN
    ALTER TABLE public.tools 
    ADD COLUMN tasks TEXT[] DEFAULT '{}';
  END IF;
END $$;

COMMENT ON COLUMN public.tools.tasks IS 'Array of use cases/tasks the tool can help with';

-- =============================================================================
-- 5. ADD PRICING DETAILS JSON FIELD
-- =============================================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                 WHERE table_name = 'tools' AND column_name = 'pricing_details') THEN
    ALTER TABLE public.tools 
    ADD COLUMN pricing_details JSONB DEFAULT NULL;
  END IF;
END $$;

COMMENT ON COLUMN public.tools.pricing_details IS 'Detailed pricing information: {free: {...}, pro: {...}, enterprise: {...}}';

-- =============================================================================
-- 6. VIEW FOR TOOLS WITH ANALYTICS
-- =============================================================================

CREATE OR REPLACE VIEW public.tools_with_analytics AS
SELECT 
  t.*,
  COALESCE(
    (SELECT COUNT(*) FROM public.tool_clicks tc WHERE tc.tool_id = t.id AND tc.clicked_at > NOW() - INTERVAL '7 days'),
    0
  ) AS clicks_last_7_days,
  COALESCE(
    (SELECT COUNT(*) FROM public.tool_clicks tc WHERE tc.tool_id = t.id AND tc.clicked_at > NOW() - INTERVAL '30 days'),
    0
  ) AS clicks_last_30_days
FROM public.tools t;

-- Grant access to the view
GRANT SELECT ON public.tools_with_analytics TO anon, authenticated;
