-- Skipped destructive migration (20260104_migrate_to_openai.sql)
-- This migration attempted to drop the embedding column to switch to OpenAI.
-- We are currently using Gemini (768 dimensions), so this is obsolete and dangerous.
