// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { createSupabaseNetworkError, isSupabaseNetworkError } from "@/lib/supabaseNetwork";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://pzpplippcdmkmwnzmdbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "sb_publishable_LrMo9PCEEA3mhoJiHfySQA_H3fAylDZ";

if (!SUPABASE_URL) {
  console.error("Missing VITE_SUPABASE_URL environment variable");
}
if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error("Missing VITE_SUPABASE_PUBLISHABLE_KEY environment variable");
}

const getSupabaseProjectRef = () => {
  try {
    return new URL(SUPABASE_URL).hostname.split(".")[0] || "";
  } catch {
    return "";
  }
};

const currentSupabaseProjectRef = getSupabaseProjectRef();
const currentAuthStorageKey = currentSupabaseProjectRef
  ? `sb-${currentSupabaseProjectRef}-auth-token`
  : "sb-auth-token";

const clearStaleSupabaseAuthKeys = () => {
  if (typeof window === "undefined") {
    return;
  }

  try {
    const staleAuthKeys = Object.keys(window.localStorage).filter(
      (key) => key.startsWith("sb-") && key.endsWith("-auth-token") && key !== currentAuthStorageKey,
    );

    staleAuthKeys.forEach((key) => window.localStorage.removeItem(key));
  } catch (error) {
    console.warn("Failed to clear stale Supabase auth keys", error);
  }
};

clearStaleSupabaseAuthKeys();

const globalFetch = globalThis.fetch.bind(globalThis);
const supabaseHost = new URL(SUPABASE_URL).host;
let supabaseNetworkUnavailable = false;

if (typeof window !== "undefined") {
  window.addEventListener("online", () => {
    supabaseNetworkUnavailable = false;
  });
}

const isSupabaseRequest = (input: string | URL | Request) => {
  try {
    const requestUrl =
      input instanceof Request
        ? new URL(input.url)
        : new URL(typeof input === "string" ? input : input.toString(), SUPABASE_URL);

    return requestUrl.host === supabaseHost;
  } catch {
    return false;
  }
};

const supabaseFetch: typeof fetch = async (input, init) => {
  if (!isSupabaseRequest(input)) {
    return globalFetch(input, init);
  }

  if (supabaseNetworkUnavailable) {
    throw createSupabaseNetworkError("cached offline host");
  }

  try {
    const response = await globalFetch(input, init);
    supabaseNetworkUnavailable = false;
    return response;
  } catch (error) {
    supabaseNetworkUnavailable = true;
    throw createSupabaseNetworkError(error);
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    storageKey: currentAuthStorageKey,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: supabaseFetch,
  },
  realtime: {
    params: {
      eventsPerSecond: 2,
    },
  },
});

export { isSupabaseNetworkError };
